import { type Expr } from './expr';
import { type Stack } from '../state';
export declare const PUSHES: {
    PUSH1: typeof push;
    PUSH2: typeof push;
    PUSH3: typeof push;
    PUSH4: typeof push;
    PUSH5: typeof push;
    PUSH6: typeof push;
    PUSH7: typeof push;
    PUSH8: typeof push;
    PUSH9: typeof push;
    PUSH10: typeof push;
    PUSH11: typeof push;
    PUSH12: typeof push;
    PUSH13: typeof push;
    PUSH14: typeof push;
    PUSH15: typeof push;
    PUSH16: typeof push;
    PUSH17: typeof push;
    PUSH18: typeof push;
    PUSH19: typeof push;
    PUSH20: typeof push;
    PUSH21: typeof push;
    PUSH22: typeof push;
    PUSH23: typeof push;
    PUSH24: typeof push;
    PUSH25: typeof push;
    PUSH26: typeof push;
    PUSH27: typeof push;
    PUSH28: typeof push;
    PUSH29: typeof push;
    PUSH30: typeof push;
    PUSH31: typeof push;
    PUSH32: typeof push;
};
declare function push(pushData: Uint8Array, stack: Stack<Expr>): void;
export declare function STACK<E>(): {
    POP: (stack: Stack<Expr>) => void;
    DUP1: (stack: Stack<E>) => void;
    DUP2: (stack: Stack<E>) => void;
    DUP3: (stack: Stack<E>) => void;
    DUP4: (stack: Stack<E>) => void;
    DUP5: (stack: Stack<E>) => void;
    DUP6: (stack: Stack<E>) => void;
    DUP7: (stack: Stack<E>) => void;
    DUP8: (stack: Stack<E>) => void;
    DUP9: (stack: Stack<E>) => void;
    DUP10: (stack: Stack<E>) => void;
    DUP11: (stack: Stack<E>) => void;
    DUP12: (stack: Stack<E>) => void;
    DUP13: (stack: Stack<E>) => void;
    DUP14: (stack: Stack<E>) => void;
    DUP15: (stack: Stack<E>) => void;
    DUP16: (stack: Stack<E>) => void;
    SWAP1: (stack: Stack<E>) => void;
    SWAP2: (stack: Stack<E>) => void;
    SWAP3: (stack: Stack<E>) => void;
    SWAP4: (stack: Stack<E>) => void;
    SWAP5: (stack: Stack<E>) => void;
    SWAP6: (stack: Stack<E>) => void;
    SWAP7: (stack: Stack<E>) => void;
    SWAP8: (stack: Stack<E>) => void;
    SWAP9: (stack: Stack<E>) => void;
    SWAP10: (stack: Stack<E>) => void;
    SWAP11: (stack: Stack<E>) => void;
    SWAP12: (stack: Stack<E>) => void;
    SWAP13: (stack: Stack<E>) => void;
    SWAP14: (stack: Stack<E>) => void;
    SWAP15: (stack: Stack<E>) => void;
    SWAP16: (stack: Stack<E>) => void;
};
export {};
