# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuring-automatically-generated-release-notes

changelog:
  categories:
    - title: New Features 🎉
      labels:
        - feature
    - title: Bug Fixes 🐛
      labels:
        - bug
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Documentation 📝
      labels:
        - docs
    - title: Dev & CLI Dependency Upgrades ⤴️
      labels:
        - dependencies
    - title: Internal Changes 🏠
      labels:
        - "*"
