# This configuration[1] is used when `mocha` is invoked directly
# from the command line.
#
# [1] https://mochajs.org/#configuring-mocha-nodejs

# https://mochajs.org/#-enable-source-maps
enable-source-maps: true

# Fetch and cache `solc` compilers
# https://mochajs.org/#global-setup-fixtures
require: scripts/solc.mjs

# https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
spec:
  - dist/test/**/*.{test,check}.js
