import { basename } from 'path';
import { utils } from 'ethers';

const interfaces = {};

interfaces.ERC165 = ['supportsInterface(bytes4)'];

interfaces.ERC20 = [
    'totalSupply()',
    'balanceOf(address)',
    'transfer(address,uint256)',
    'transferFrom(address,address,uint256)',
    'approve(address,uint256)',
    'allowance(address,address)',
];

interfaces.ERC20Metadata = ['name()', 'symbol()', 'decimals()', ...interfaces.ERC20];

interfaces.ERC721 = [
    'balanceOf(address)',
    'ownerOf(uint256)',
    'safeTransferFrom(address,address,uint256,bytes)',
    'safeTransferFrom(address,address,uint256)',
    'transferFrom(address,address,uint256)',
    'approve(address,uint256)',
    'setApprovalForAll(address,bool)',
    'getApproved(uint256)',
    'isApprovedForAll(address,address)',
    ...interfaces.ERC165,
];

function main() {
    const src = {};
    for (const [name, erc] of Object.entries(interfaces)) {
        const selectors = {};
        for (const sig of erc) {
            const name = sig.replace(/\(/, '_').replace(/\)/g, '_').replace(/,/g, '_');

            selectors[name] = utils.keccak256(utils.toUtf8Bytes(sig)).substring(2, 10);
        }
        src[name] = {
            includes: Object.values(selectors),
            selectors,
        };
    }

    console.info(`// Autogenerated by \`${basename(import.meta.url)}\`. DO NOT MODIFY`);
    console.info('export default', src, ';');
}

main();
