import { EVM } from '../evm';
import { Opcode } from '../opcode';
declare const _default: {
    STOP: (_opcode: Opcode, state: EVM) => void;
    ADD: (_opcode: Opcode, { stack }: EVM) => void;
    MUL: (_opcode: Opcode, { stack }: EVM) => void;
    SUB: (_opcode: Opcode, { stack }: EVM) => void;
    DIV: typeof div;
    SDIV: typeof div;
    MOD: typeof mod;
    SMOD: typeof mod;
    ADDMOD: (_opcode: Opcode, { stack }: EVM) => void;
    MULMOD: (_opcode: Opcode, { stack }: EVM) => void;
    EXP: (_opcode: Opcode, { stack }: EVM) => void;
    SIGNEXTEND: (_opcode: Opcode, { stack }: EVM) => void;
    LT: typeof lt;
    GT: typeof gt;
    SLT: typeof lt;
    SGT: typeof gt;
    EQ: (_opcode: Opcode, { stack }: EVM) => void;
    ISZERO: (_opcode: Opcode, { stack }: EVM) => void;
    AND: (_opcode: Opcode, { stack }: EVM) => void;
    OR: (_opcode: Opcode, { stack }: EVM) => void;
    XOR: (_opcode: Opcode, { stack }: EVM) => void;
    NOT: (_opcode: Opcode, { stack }: EVM) => void;
    BYTE: (_opcode: Opcode, { stack }: EVM) => void;
    SHL: (_opcode: Opcode, { stack }: EVM) => void;
    SHR: (_opcode: Opcode, { stack }: EVM) => void;
    SAR: (_opcode: Opcode, { stack }: EVM) => void;
    SHA3: (_opcode: Opcode, { stack, memory }: EVM) => void;
    ADDRESS: (_opcode: Opcode, { stack }: EVM) => void;
    BALANCE: (_opcode: Opcode, { stack }: EVM) => void;
    ORIGIN: (_opcode: Opcode, { stack }: EVM) => void;
    CALLER: (_opcode: Opcode, { stack }: EVM) => void;
    CALLVALUE: (_opcode: Opcode, { stack }: EVM) => void;
    CALLDATALOAD: (_opcode: Opcode, { stack }: EVM) => void;
    CALLDATASIZE: (_opcode: Opcode, { stack }: EVM) => void;
    CALLDATACOPY: (_opcode: Opcode, { stack, memory }: EVM) => void;
    CODESIZE: (_opcode: Opcode, { stack }: EVM) => void;
    CODECOPY: (_opcode: Opcode, { stack, memory }: EVM) => void;
    GASPRICE: (_opcode: Opcode, { stack }: EVM) => void;
    EXTCODESIZE: (_opcode: Opcode, { stack }: EVM) => void;
    EXTCODECOPY: (_opcode: Opcode, { stack, memory }: EVM) => void;
    RETURNDATASIZE: (_opcode: Opcode, { stack }: EVM) => void;
    RETURNDATACOPY: (_opcode: Opcode, { stack, memory }: EVM) => void;
    EXTCODEHASH: (_opcode: Opcode, { stack }: EVM) => void;
    BLOCKHASH: (_opcode: Opcode, { stack }: EVM) => void;
    COINBASE: (_opcode: Opcode, { stack }: EVM) => void;
    TIMESTAMP: (_opcode: Opcode, { stack }: EVM) => void;
    NUMBER: (_opcode: Opcode, { stack }: EVM) => void;
    DIFFICULTY: (_opcode: Opcode, { stack }: EVM) => void;
    GASLIMIT: (_opcode: Opcode, { stack }: EVM) => void;
    POP: (_opcode: Opcode, { stack }: EVM) => void;
    MLOAD: (_opcode: Opcode, { stack, memory }: EVM) => void;
    MSTORE: typeof mstore;
    MSTORE8: typeof mstore;
    SLOAD: (_opcode: Opcode, state: EVM) => void;
    SSTORE: (_opcode: Opcode, state: EVM) => void;
    JUMP: (opcode: Opcode, state: EVM) => void;
    JUMPI: (opcode: Opcode, state: EVM) => void;
    PC: (opcode: Opcode, { stack }: EVM) => void;
    MSIZE: (_opcode: Opcode, { stack }: EVM) => void;
    GAS: (_opcode: Opcode, { stack }: EVM) => void;
    JUMPDEST: (_opcode: Opcode, _state: EVM) => void;
    PUSH1: typeof push;
    PUSH2: typeof push;
    PUSH3: typeof push;
    PUSH4: typeof push;
    PUSH5: typeof push;
    PUSH6: typeof push;
    PUSH7: typeof push;
    PUSH8: typeof push;
    PUSH9: typeof push;
    PUSH10: typeof push;
    PUSH11: typeof push;
    PUSH12: typeof push;
    PUSH13: typeof push;
    PUSH14: typeof push;
    PUSH15: typeof push;
    PUSH16: typeof push;
    PUSH17: typeof push;
    PUSH18: typeof push;
    PUSH19: typeof push;
    PUSH20: typeof push;
    PUSH21: typeof push;
    PUSH22: typeof push;
    PUSH23: typeof push;
    PUSH24: typeof push;
    PUSH25: typeof push;
    PUSH26: typeof push;
    PUSH27: typeof push;
    PUSH28: typeof push;
    PUSH29: typeof push;
    PUSH30: typeof push;
    PUSH31: typeof push;
    PUSH32: typeof push;
    DUP1: (_opcode: Opcode, { stack }: EVM) => void;
    DUP2: (_opcode: Opcode, { stack }: EVM) => void;
    DUP3: (_opcode: Opcode, { stack }: EVM) => void;
    DUP4: (_opcode: Opcode, { stack }: EVM) => void;
    DUP5: (_opcode: Opcode, { stack }: EVM) => void;
    DUP6: (_opcode: Opcode, { stack }: EVM) => void;
    DUP7: (_opcode: Opcode, { stack }: EVM) => void;
    DUP8: (_opcode: Opcode, { stack }: EVM) => void;
    DUP9: (_opcode: Opcode, { stack }: EVM) => void;
    DUP10: (_opcode: Opcode, { stack }: EVM) => void;
    DUP11: (_opcode: Opcode, { stack }: EVM) => void;
    DUP12: (_opcode: Opcode, { stack }: EVM) => void;
    DUP13: (_opcode: Opcode, { stack }: EVM) => void;
    DUP14: (_opcode: Opcode, { stack }: EVM) => void;
    DUP15: (_opcode: Opcode, { stack }: EVM) => void;
    DUP16: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP1: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP2: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP3: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP4: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP5: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP6: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP7: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP8: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP9: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP10: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP11: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP12: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP13: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP14: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP15: (_opcode: Opcode, { stack }: EVM) => void;
    SWAP16: (_opcode: Opcode, { stack }: EVM) => void;
    LOG0: (_opcode: Opcode, state: EVM) => void;
    LOG1: (_opcode: Opcode, state: EVM) => void;
    LOG2: (_opcode: Opcode, state: EVM) => void;
    LOG3: (_opcode: Opcode, state: EVM) => void;
    LOG4: (_opcode: Opcode, state: EVM) => void;
    CREATE: (_opcode: Opcode, state: EVM) => void;
    CALL: (_opcode: Opcode, { stack, memory }: EVM) => void;
    CALLCODE: (_opcode: Opcode, { stack }: EVM) => void;
    RETURN: (_opcode: Opcode, state: EVM) => void;
    DELEGATECALL: (_opcode: Opcode, { stack }: EVM) => void;
    CREATE2: (_opcode: Opcode, { stack }: EVM) => void;
    STATICCALL: (_opcode: Opcode, { stack }: EVM) => void;
    REVERT: (_opcode: Opcode, state: EVM) => void;
    INVALID: (opcode: Opcode, state: EVM) => void;
    SELFDESTRUCT: (_opcode: Opcode, state: EVM) => void;
};
export default _default;
declare function div(_opcode: Opcode, { stack }: EVM): void;
declare function mod(_opcode: Opcode, { stack }: EVM): void;
declare function lt(_opcode: Opcode, { stack }: EVM): void;
declare function gt(_opcode: Opcode, { stack }: EVM): void;
declare function push(opcode: Opcode, { stack }: EVM): void;
declare function mstore(_opcode: Opcode, { stack, memory, instructions }: EVM): void;
