export declare const STOP = 0;
export declare const ADD = 1;
export declare const MUL = 2;
export declare const SUB = 3;
export declare const DIV = 4;
export declare const SDIV = 5;
export declare const MOD = 6;
export declare const SMOD = 7;
export declare const ADDMOD = 8;
export declare const MULMOD = 9;
export declare const EXP = 10;
export declare const SIGNEXTEND = 11;
export declare const LT = 16;
export declare const GT = 17;
export declare const SLT = 18;
export declare const SGT = 19;
export declare const EQ = 20;
export declare const ISZERO = 21;
export declare const AND = 22;
export declare const OR = 23;
export declare const XOR = 24;
export declare const NOT = 25;
export declare const BYTE = 26;
export declare const SHL = 27;
export declare const SHR = 28;
export declare const SAR = 29;
export declare const SHA3 = 32;
export declare const ADDRESS = 48;
export declare const BALANCE = 49;
export declare const ORIGIN = 50;
export declare const CALLER = 51;
export declare const CALLVALUE = 52;
export declare const CALLDATALOAD = 53;
export declare const CALLDATASIZE = 54;
export declare const CALLDATACOPY = 55;
export declare const CODESIZE = 56;
export declare const CODECOPY = 57;
export declare const GASPRICE = 58;
export declare const EXTCODESIZE = 59;
export declare const EXTCODECOPY = 60;
export declare const RETURNDATASIZE = 61;
export declare const RETURNDATACOPY = 62;
export declare const EXTCODEHASH = 63;
export declare const BLOCKHASH = 64;
export declare const COINBASE = 65;
export declare const TIMESTAMP = 66;
export declare const NUMBER = 67;
export declare const DIFFICULTY = 68;
export declare const GASLIMIT = 69;
export declare const POP = 80;
export declare const MLOAD = 81;
export declare const MSTORE = 82;
export declare const MSTORE8 = 83;
export declare const SLOAD = 84;
export declare const SSTORE = 85;
export declare const JUMP = 86;
export declare const JUMPI = 87;
export declare const PC = 88;
export declare const MSIZE = 89;
export declare const GAS = 90;
export declare const JUMPDEST = 91;
export declare const PUSH1 = 96;
export declare const PUSH2 = 97;
export declare const PUSH3 = 98;
export declare const PUSH4 = 99;
export declare const PUSH5 = 100;
export declare const PUSH6 = 101;
export declare const PUSH7 = 102;
export declare const PUSH8 = 103;
export declare const PUSH9 = 104;
export declare const PUSH10 = 105;
export declare const PUSH11 = 106;
export declare const PUSH12 = 107;
export declare const PUSH13 = 108;
export declare const PUSH14 = 109;
export declare const PUSH15 = 110;
export declare const PUSH16 = 111;
export declare const PUSH17 = 112;
export declare const PUSH18 = 113;
export declare const PUSH19 = 114;
export declare const PUSH20 = 115;
export declare const PUSH21 = 116;
export declare const PUSH22 = 117;
export declare const PUSH23 = 118;
export declare const PUSH24 = 119;
export declare const PUSH25 = 120;
export declare const PUSH26 = 121;
export declare const PUSH27 = 122;
export declare const PUSH28 = 123;
export declare const PUSH29 = 124;
export declare const PUSH30 = 125;
export declare const PUSH31 = 126;
export declare const PUSH32 = 127;
export declare const DUP1 = 128;
export declare const DUP2 = 129;
export declare const DUP3 = 130;
export declare const DUP4 = 131;
export declare const DUP5 = 132;
export declare const DUP6 = 133;
export declare const DUP7 = 134;
export declare const DUP8 = 135;
export declare const DUP9 = 136;
export declare const DUP10 = 137;
export declare const DUP11 = 138;
export declare const DUP12 = 139;
export declare const DUP13 = 140;
export declare const DUP14 = 141;
export declare const DUP15 = 142;
export declare const DUP16 = 143;
export declare const SWAP1 = 144;
export declare const SWAP2 = 145;
export declare const SWAP3 = 146;
export declare const SWAP4 = 147;
export declare const SWAP5 = 148;
export declare const SWAP6 = 149;
export declare const SWAP7 = 150;
export declare const SWAP8 = 151;
export declare const SWAP9 = 152;
export declare const SWAP10 = 153;
export declare const SWAP11 = 154;
export declare const SWAP12 = 155;
export declare const SWAP13 = 156;
export declare const SWAP14 = 157;
export declare const SWAP15 = 158;
export declare const SWAP16 = 159;
export declare const LOG0 = 160;
export declare const LOG1 = 161;
export declare const LOG2 = 162;
export declare const LOG3 = 163;
export declare const LOG4 = 164;
export declare const CREATE = 240;
export declare const CALL = 241;
export declare const CALLCODE = 242;
export declare const RETURN = 243;
export declare const DELEGATECALL = 244;
export declare const CREATE2 = 245;
export declare const STATICCALL = 250;
export declare const REVERT = 253;
export declare const INVALID = 254;
export declare const SELFDESTRUCT = 255;
export declare const codes: {
    0: string;
    1: string;
    2: string;
    3: string;
    4: string;
    5: string;
    6: string;
    7: string;
    8: string;
    9: string;
    10: string;
    11: string;
    16: string;
    17: string;
    18: string;
    19: string;
    20: string;
    21: string;
    22: string;
    23: string;
    24: string;
    25: string;
    26: string;
    27: string;
    28: string;
    29: string;
    32: string;
    48: string;
    49: string;
    50: string;
    51: string;
    52: string;
    53: string;
    54: string;
    55: string;
    56: string;
    57: string;
    58: string;
    59: string;
    60: string;
    61: string;
    62: string;
    63: string;
    64: string;
    65: string;
    66: string;
    67: string;
    68: string;
    69: string;
    80: string;
    81: string;
    82: string;
    83: string;
    84: string;
    85: string;
    86: string;
    87: string;
    88: string;
    89: string;
    90: string;
    91: string;
    96: string;
    97: string;
    98: string;
    99: string;
    100: string;
    101: string;
    102: string;
    103: string;
    104: string;
    105: string;
    106: string;
    107: string;
    108: string;
    109: string;
    110: string;
    111: string;
    112: string;
    113: string;
    114: string;
    115: string;
    116: string;
    117: string;
    118: string;
    119: string;
    120: string;
    121: string;
    122: string;
    123: string;
    124: string;
    125: string;
    126: string;
    127: string;
    128: string;
    129: string;
    130: string;
    131: string;
    132: string;
    133: string;
    134: string;
    135: string;
    136: string;
    137: string;
    138: string;
    139: string;
    140: string;
    141: string;
    142: string;
    143: string;
    144: string;
    145: string;
    146: string;
    147: string;
    148: string;
    149: string;
    150: string;
    151: string;
    152: string;
    153: string;
    154: string;
    155: string;
    156: string;
    157: string;
    158: string;
    159: string;
    160: string;
    161: string;
    162: string;
    163: string;
    164: string;
    240: string;
    241: string;
    242: string;
    243: string;
    244: string;
    245: string;
    250: string;
    253: string;
    254: string;
    255: string;
};
export declare const names: {
    STOP: number;
    ADD: number;
    MUL: number;
    SUB: number;
    DIV: number;
    SDIV: number;
    MOD: number;
    SMOD: number;
    ADDMOD: number;
    MULMOD: number;
    EXP: number;
    SIGNEXTEND: number;
    LT: number;
    GT: number;
    SLT: number;
    SGT: number;
    EQ: number;
    ISZERO: number;
    AND: number;
    OR: number;
    XOR: number;
    NOT: number;
    BYTE: number;
    SHL: number;
    SHR: number;
    SAR: number;
    SHA3: number;
    ADDRESS: number;
    BALANCE: number;
    ORIGIN: number;
    CALLER: number;
    CALLVALUE: number;
    CALLDATALOAD: number;
    CALLDATASIZE: number;
    CALLDATACOPY: number;
    CODESIZE: number;
    CODECOPY: number;
    GASPRICE: number;
    EXTCODESIZE: number;
    EXTCODECOPY: number;
    RETURNDATASIZE: number;
    RETURNDATACOPY: number;
    EXTCODEHASH: number;
    BLOCKHASH: number;
    COINBASE: number;
    TIMESTAMP: number;
    NUMBER: number;
    DIFFICULTY: number;
    GASLIMIT: number;
    POP: number;
    MLOAD: number;
    MSTORE: number;
    MSTORE8: number;
    SLOAD: number;
    SSTORE: number;
    JUMP: number;
    JUMPI: number;
    PC: number;
    MSIZE: number;
    GAS: number;
    JUMPDEST: number;
    PUSH1: number;
    PUSH2: number;
    PUSH3: number;
    PUSH4: number;
    PUSH5: number;
    PUSH6: number;
    PUSH7: number;
    PUSH8: number;
    PUSH9: number;
    PUSH10: number;
    PUSH11: number;
    PUSH12: number;
    PUSH13: number;
    PUSH14: number;
    PUSH15: number;
    PUSH16: number;
    PUSH17: number;
    PUSH18: number;
    PUSH19: number;
    PUSH20: number;
    PUSH21: number;
    PUSH22: number;
    PUSH23: number;
    PUSH24: number;
    PUSH25: number;
    PUSH26: number;
    PUSH27: number;
    PUSH28: number;
    PUSH29: number;
    PUSH30: number;
    PUSH31: number;
    PUSH32: number;
    DUP1: number;
    DUP2: number;
    DUP3: number;
    DUP4: number;
    DUP5: number;
    DUP6: number;
    DUP7: number;
    DUP8: number;
    DUP9: number;
    DUP10: number;
    DUP11: number;
    DUP12: number;
    DUP13: number;
    DUP14: number;
    DUP15: number;
    DUP16: number;
    SWAP1: number;
    SWAP2: number;
    SWAP3: number;
    SWAP4: number;
    SWAP5: number;
    SWAP6: number;
    SWAP7: number;
    SWAP8: number;
    SWAP9: number;
    SWAP10: number;
    SWAP11: number;
    SWAP12: number;
    SWAP13: number;
    SWAP14: number;
    SWAP15: number;
    SWAP16: number;
    LOG0: number;
    LOG1: number;
    LOG2: number;
    LOG3: number;
    LOG4: number;
    CREATE: number;
    CALL: number;
    CALLCODE: number;
    RETURN: number;
    DELEGATECALL: number;
    CREATE2: number;
    STATICCALL: number;
    REVERT: number;
    INVALID: number;
    SELFDESTRUCT: number;
};
