#!/usr/bin/env node

/* eslint-disable @typescript-eslint/no-unsafe-argument */
/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable no-undef */

import { basename } from 'path';
import { EventFragment, FunctionFragment, keccak256, toUtf8Bytes } from 'ethers';
import { readFileSync } from 'fs';

import solc from 'solc';

function main() {
    const content = readFileSync('./scripts/ercs.sol', 'utf-8');
    const input = {
        language: 'Solidity',
        sources: { SOURCE: { content } },
        settings: { outputSelection: { '*': { '*': ['abi'] } } },
    };
    const output = solc.compile(JSON.stringify(input));
    /** @type {import('./solc').SolcOutput} */
    const { errors, contracts } = JSON.parse(output);
    if (errors) {
        console.error(errors);
        process.exit(1);
    }

    const src = {};
    for (const [name, { abi }] of Object.entries(contracts['SOURCE'])) {
        const functions = {};
        const events = {};
        for (const member of abi) {
            if (member.type === 'function') {
                const sig = FunctionFragment.from(member).format('sighash');
                const name = sig.replace(/\(/, '_').replace(/\)/g, '_').replace(/,/g, '_');
                functions[name] = keccak256(toUtf8Bytes(sig)).substring(2, 10);
            } else if (member.type === 'event') {
                const sig = EventFragment.from(member).format('sighash');
                const name = sig.replace(/\(/, '_').replace(/\)/g, '_').replace(/,/g, '_');
                events[name] = keccak256(toUtf8Bytes(sig)).substring(2);
            }
        }
        src[name] = {
            selectors: Object.values(functions),
            topics: Object.values(events),
            functions,
            events,
        };
    }

    console.info(`// Autogenerated by \`${basename(import.meta.url)}\`. DO NOT MODIFY`);
    console.info('export default', src, ';');
}

main();
