#!/usr/bin/env node
/* eslint-env node */

import { basename } from 'path';
import { EventFragment, FunctionFragment } from 'ethers';
import { readFileSync } from 'fs';

import solc, { type SolcOutput } from 'solc';

type Table = { [hash: string]: string; };

function main() {
    const input = {
        language: 'Solidity',
        sources: { 'ercs.sol': { content: readFileSync('./scripts/ercs.sol', 'utf-8') } },
        settings: { outputSelection: { '*': { '*': ['abi'] } } },
    };
    const output = solc.compile(JSON.stringify(input));
    const { errors, contracts }: SolcOutput = JSON.parse(output);
    if (errors) {
        console.error(errors);
        process.exit(1);
    }

    const src: { [name: string]: { selectors: string[]; topics: string[]; functions: Table; events: Table; }; } = {};
    for (const [name, { abi }] of Object.entries(contracts['ercs.sol'])) {
        const functions: Table = {};
        const events: Table = {};
        for (const member of abi) {
            if (member.type === 'function') {
                const fn = FunctionFragment.from(member);
                functions[fn.selector.substring(2, 10)] = fn.format('full');
            } else if (member.type === 'event') {
                const ev = EventFragment.from(member);
                events[ev.topicHash.substring(2)] = ev.format('full');
            }
        }
        src[name] = {
            selectors: Object.keys(functions),
            topics: Object.keys(events),
            functions,
            events,
        };
    }

    console.info(`// Autogenerated by \`${basename(import.meta.url)}\`. DO NOT MODIFY`);
    console.info('export default', src, ';');
}

main();
