export default {
    'Compound-0x3FDA67f7583380E67ef93072294a7fAc882FD7E7': {
        events: [
            'Failure(uint256,uint256,uint256)',
            'NewOriginationFee(uint256,uint256)',
            'SetPaused(bool)',
            'NewOracle(address,address)',
            'SetMarketInterestRateModel(address,address)',
            'NewPendingAdmin(address,address)',
            'SuspendedMarket(address)',
            'NewAdmin(address,address)',
        ],
        functions: [
            '_setOriginationFee(uint256)',
            'pendingAdmin()',
            'getBorrowBalance(address,address)',
            '_setPaused(bool)',
            '_setOracle(address)',
            '_withdrawEquity(address,uint256)',
            'borrow(address,uint256)',
            'paused()',
            '_setMarketInterestRateModel(address,address)',
            'assetPrices(address)',
            'getAccountLiquidity(address)',
            'getCollateralMarketsLength()',
            'oracle()',
            'liquidationDiscount()',
            'markets(address)',
            'calculateAccountValues(address)',
            'repayBorrow(address,uint256)',
            'collateralRatio()',
            '_setPendingAdmin(address)',
            'supplyBalances(address,address)',
            'originationFee()',
            'getSupplyBalance(address,address)',
            'collateralMarkets(uint256)',
            '_supportMarket(address,address)',
            '_setRiskParameters(uint256,uint256)',
            '_suspendMarket(address)',
            'liquidateBorrow(address,address,address,uint256)',
            '_acceptAdmin()',
            'supply(address,uint256)',
            'withdraw(address,uint256)',
            'admin()',
            'borrowBalances(address,address)',
        ],
    },

    'CryptoKitties-0x06012c8cf97BEaD5deAe237070F9587f8E7A266d': {
        events: [
            'Approval(address,address,uint256)',
            'Transfer(address,address,uint256)',
            'Birth(address,uint256,uint256,uint256,uint256)',
            'ContractUpgrade(address)',
        ],
        functions: [
            'createPromoKitty(uint256,address)',
            'setNewAddress(address)',
            'supportsInterface(bytes4)',
            'cfoAddress()',
            'tokenMetadata(uint256,string)',
            'promoCreatedCount()',
            'name()',
            'approve(address,uint256)',
            'ceoAddress()',
            'GEN0_STARTING_PRICE()',
            'setSiringAuctionAddress(address)',
            'totalSupply()',
            'isPregnant(uint256)',
            'GEN0_AUCTION_DURATION()',
            'siringAuction()',
            'transferFrom(address,address,uint256)',
            'setGeneScienceAddress(address)',
            'setCEO(address)',
            'setCOO(address)',
            'createSaleAuction(uint256,uint256,uint256,uint256)',
            'unpause()',
            'canBreedWith(uint256,uint256)',
            'createSiringAuction(uint256,uint256,uint256,uint256)',
            'setAutoBirthFee(uint256)',
            'approveSiring(address,uint256)',
            'setCFO(address)',
            'setSecondsPerBlock(uint256)',
            'paused()',
            'withdrawBalance()',
            'ownerOf(uint256)',
            'GEN0_CREATION_LIMIT()',
            'newContractAddress()',
            'setSaleAuctionAddress(address)',
            'balanceOf(address)',
            'secondsPerBlock()',
            'pause()',
            'tokensOfOwner(address)',
            'giveBirth(uint256)',
            'withdrawAuctionBalances()',
            'symbol()',
            'cooldowns(uint256)',
            'transfer(address,uint256)',
            'cooAddress()',
            'autoBirthFee()',
            'erc721Metadata()',
            'createGen0Auction(uint256)',
            'isReadyToBreed(uint256)',
            'PROMO_CREATION_LIMIT()',
            'setMetadataAddress(address)',
            'saleAuction()',
            'getKitty(uint256)',
            'bidOnSiringAuction(uint256,uint256)',
            'gen0CreatedCount()',
            'geneScience()',
            'breedWithAuto(uint256,uint256)',
        ],
    },

    'DAI-0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359': {
        events: ['Approval(address,address,uint256)', 'LogSetOwner(address)'],
        functions: [
            'name()',
            'stop()',
            'approve(address,uint256)',
            'setOwner(address)',
            'totalSupply()',
            'transferFrom(address,address,uint256)',
            'decimals()',
            'mint(address,uint256)',
            'burn(uint256)',
            'setName(bytes32)',
            'balanceOf(address)',
            'stopped()',
            'setAuthority(address)',
            'owner()',
            'symbol()',
            'burn(address,uint256)',
            'mint(uint256)',
            'transfer(address,uint256)',
            'push(address,uint256)',
            'move(address,address,uint256)',
            'start()',
            'authority()',
            'approve(address)',
            'allowance(address,address)',
            'pull(address,uint256)',
        ],
    },

    'ENS-0x314159265dD8dbb310642f98f50C066173C1259b': {
        events: [],
        functions: [],
    },

    'UnicornToken-0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7': {
        events: ['Transfer(address,address,uint256)', 'FrozenFunds(address,bool)'],
        functions: [
            'name()',
            'approve(address,uint256)',
            'totalSupply()',
            'transferFrom(address,address,uint256)',
            'decimals()',
            'balanceOf(address)',
            'mintToken(address,uint256)',
            'owner()',
            'symbol()',
            'transfer(address,uint256)',
            'frozenAccount(address)',
            'allowance(address,address)',
            'freezeAccount(address,bool)',
            'transferOwnership(address)',
        ],
    },

    'USDC-0x5425890298aed601595a70AB815c96711a31Bc65': {
        events: [],
        functions: [
            'upgradeTo(address)',
            'upgradeToAndCall(address,bytes)',
            'changeAdmin(address)',
            'implementation()',
            'admin()',
        ],
    },

    'WETH-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2': {
        events: [
            'Deposit(address,uint256)',
            'Approval(address,address,uint256)',
            'Transfer(address,address,uint256)',
            'Withdrawal(address,uint256)',
        ],
        functions: [
            'name()',
            'approve(address,uint256)',
            'totalSupply()',
            'transferFrom(address,address,uint256)',
            'withdraw(uint256)',
            'decimals()',
            'balanceOf(address)',
            'symbol()',
            'transfer(address,uint256)',
            'deposit()',
            'allowance(address,address)',
        ],
    },
};
