// Autogenerated by `ercs.mjs`. DO NOT MODIFY
export default {
    ERC1155: {
        selectors: [
            '00fdd58e',
            '4e1273f4',
            'e985e9c5',
            '2eb2c2d6',
            'f242432a',
            'a22cb465',
            '01ffc9a7'
        ],
        topics: [
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
            '4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb',
            'c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62',
            '6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b'
        ],
        functions: {
            '00fdd58e': 'function balanceOf(address _owner, uint256 _id) view returns (uint256)',
            '4e1273f4': 'function balanceOfBatch(address[] _owners, uint256[] _ids) view returns (uint256[])',
            e985e9c5: 'function isApprovedForAll(address _owner, address _operator) view returns (bool)',
            '2eb2c2d6': 'function safeBatchTransferFrom(address _from, address _to, uint256[] _ids, uint256[] _values, bytes _data)',
            f242432a: 'function safeTransferFrom(address _from, address _to, uint256 _id, uint256 _value, bytes _data)',
            a22cb465: 'function setApprovalForAll(address _operator, bool _approved)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)'
        },
        events: {
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31': 'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
            '4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb': 'event TransferBatch(address indexed _operator, address indexed _from, address indexed _to, uint256[] _ids, uint256[] _values)',
            c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62: 'event TransferSingle(address indexed _operator, address indexed _from, address indexed _to, uint256 _id, uint256 _value)',
            '6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b': 'event URI(string _value, uint256 indexed _id)',
        }
    },
    ERC1155MetadataURI: {
        selectors: [
            '00fdd58e',
            '4e1273f4',
            'e985e9c5',
            '2eb2c2d6',
            'f242432a',
            'a22cb465',
            '01ffc9a7',
            '0e89341c'
        ],
        topics: [
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
            '4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb',
            'c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62',
            '6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b'
        ],
        functions: {
            '00fdd58e': 'function balanceOf(address _owner, uint256 _id) view returns (uint256)',
            '4e1273f4': 'function balanceOfBatch(address[] _owners, uint256[] _ids) view returns (uint256[])',
            e985e9c5: 'function isApprovedForAll(address _owner, address _operator) view returns (bool)',
            '2eb2c2d6': 'function safeBatchTransferFrom(address _from, address _to, uint256[] _ids, uint256[] _values, bytes _data)',
            f242432a: 'function safeTransferFrom(address _from, address _to, uint256 _id, uint256 _value, bytes _data)',
            a22cb465: 'function setApprovalForAll(address _operator, bool _approved)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
            '0e89341c': 'function uri(uint256 _id) view returns (string)'
        },
        events: {
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31': 'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
            '4a39dc06d4c0dbc64b70af90fd698a233a518aa5d07e595d983b8c0526c8f7fb': 'event TransferBatch(address indexed _operator, address indexed _from, address indexed _to, uint256[] _ids, uint256[] _values)',
            c3d58168c5ae7397731d063d5bbf3d657854427343f4c083240f7aacaa2d0f62: 'event TransferSingle(address indexed _operator, address indexed _from, address indexed _to, uint256 _id, uint256 _value)',
            '6bb7ff708619ba0610cba295a58592e0451dee2622938c8755667688daf3529b': 'event URI(string _value, uint256 indexed _id)'
        }
    },
    ERC165: {
        selectors: ['01ffc9a7'],
        topics: [],
        functions: {
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
        },
        events: {},
    },
    ERC173: {
        selectors: ['8da5cb5b', '01ffc9a7', 'f2fde38b'],
        topics: ['8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0'],
        functions: {
            '8da5cb5b': 'function owner() view returns (address)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
            f2fde38b: 'function transferOwnership(address _newOwner)',
        },
        events: {
            '8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0':
                'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
        },
    },
    ERC20: {
        selectors: ['dd62ed3e', '095ea7b3', '70a08231', '18160ddd', 'a9059cbb', '23b872dd'],
        topics: [
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
            'ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
        ],
        functions: {
            dd62ed3e:
                'function allowance(address _owner, address _spender) view returns (uint256 remaining)',
            '095ea7b3': 'function approve(address _spender, uint256 _value) returns (bool success)',
            '70a08231': 'function balanceOf(address _owner) view returns (uint256 balance)',
            '18160ddd': 'function totalSupply() view returns (uint256)',
            a9059cbb: 'function transfer(address _to, uint256 _value) returns (bool success)',
            '23b872dd':
                'function transferFrom(address _from, address _to, uint256 _value) returns (bool success)',
        },
        events: {
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925':
                'event Approval(address indexed _owner, address indexed _spender, uint256 _value)',
            ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef:
                'event Transfer(address indexed _from, address indexed _to, uint256 _value)',
        },
    },
    ERC20Metadata: {
        selectors: [
            'dd62ed3e',
            '095ea7b3',
            '70a08231',
            '313ce567',
            '06fdde03',
            '95d89b41',
            '18160ddd',
            'a9059cbb',
            '23b872dd',
        ],
        topics: [
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
            'ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
        ],
        functions: {
            dd62ed3e:
                'function allowance(address _owner, address _spender) view returns (uint256 remaining)',
            '095ea7b3': 'function approve(address _spender, uint256 _value) returns (bool success)',
            '70a08231': 'function balanceOf(address _owner) view returns (uint256 balance)',
            '313ce567': 'function decimals() view returns (uint8)',
            '06fdde03': 'function name() view returns (string)',
            '95d89b41': 'function symbol() view returns (string)',
            '18160ddd': 'function totalSupply() view returns (uint256)',
            a9059cbb: 'function transfer(address _to, uint256 _value) returns (bool success)',
            '23b872dd':
                'function transferFrom(address _from, address _to, uint256 _value) returns (bool success)',
        },
        events: {
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925':
                'event Approval(address indexed _owner, address indexed _spender, uint256 _value)',
            ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef:
                'event Transfer(address indexed _from, address indexed _to, uint256 _value)',
        },
    },
    ERC721: {
        selectors: [
            '095ea7b3',
            '70a08231',
            '081812fc',
            'e985e9c5',
            '6352211e',
            '42842e0e',
            'b88d4fde',
            'a22cb465',
            '01ffc9a7',
            '23b872dd',
        ],
        topics: [
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
            'ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
        ],
        functions: {
            '095ea7b3': 'function approve(address _approved, uint256 _tokenId) payable',
            '70a08231': 'function balanceOf(address _owner) view returns (uint256)',
            '081812fc': 'function getApproved(uint256 _tokenId) view returns (address)',
            e985e9c5:
                'function isApprovedForAll(address _owner, address _operator) view returns (bool)',
            '6352211e': 'function ownerOf(uint256 _tokenId) view returns (address)',
            '42842e0e':
                'function safeTransferFrom(address _from, address _to, uint256 _tokenId) payable',
            b88d4fde:
                'function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) payable',
            a22cb465: 'function setApprovalForAll(address _operator, bool _approved)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
            '23b872dd':
                'function transferFrom(address _from, address _to, uint256 _tokenId) payable',
        },
        events: {
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925':
                'event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId)',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31':
                'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
            ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef:
                'event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId)',
        },
    },
    ERC721Enumerable: {
        selectors: [
            '095ea7b3',
            '70a08231',
            '081812fc',
            'e985e9c5',
            '6352211e',
            '42842e0e',
            'b88d4fde',
            'a22cb465',
            '01ffc9a7',
            '4f6ccce7',
            '2f745c59',
            '18160ddd',
            '23b872dd',
        ],
        topics: [
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
            'ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
        ],
        functions: {
            '095ea7b3': 'function approve(address _approved, uint256 _tokenId) payable',
            '70a08231': 'function balanceOf(address _owner) view returns (uint256)',
            '081812fc': 'function getApproved(uint256 _tokenId) view returns (address)',
            e985e9c5: 'function isApprovedForAll(address _owner, address _operator) view returns (bool)',
            '6352211e': 'function ownerOf(uint256 _tokenId) view returns (address)',
            '42842e0e': 'function safeTransferFrom(address _from, address _to, uint256 _tokenId) payable',
            b88d4fde: 'function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) payable',
            a22cb465: 'function setApprovalForAll(address _operator, bool _approved)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
            '4f6ccce7': 'function tokenByIndex(uint256 _index) view returns (uint256)',
            '2f745c59': 'function tokenOfOwnerByIndex(address _owner, uint256 _index) view returns (uint256)',
            '18160ddd': 'function totalSupply() view returns (uint256)',
            '23b872dd': 'function transferFrom(address _from, address _to, uint256 _tokenId) payable'
        },
        events: {
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925': 'event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId)',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31': 'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
            ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef: 'event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId)'
        }
    },
    ERC721Metadata: {
        selectors: [
            '095ea7b3',
            '70a08231',
            '081812fc',
            'e985e9c5',
            '06fdde03',
            '6352211e',
            '42842e0e',
            'b88d4fde',
            'a22cb465',
            '01ffc9a7',
            '95d89b41',
            'c87b56dd',
            '23b872dd',
        ],
        topics: [
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31',
            'ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef'
        ],
        functions: {
            '095ea7b3': 'function approve(address _approved, uint256 _tokenId) payable',
            '70a08231': 'function balanceOf(address _owner) view returns (uint256)',
            '081812fc': 'function getApproved(uint256 _tokenId) view returns (address)',
            e985e9c5: 'function isApprovedForAll(address _owner, address _operator) view returns (bool)',
            '06fdde03': 'function name() view returns (string)',
            '6352211e': 'function ownerOf(uint256 _tokenId) view returns (address)',
            '42842e0e': 'function safeTransferFrom(address _from, address _to, uint256 _tokenId) payable',
            b88d4fde: 'function safeTransferFrom(address _from, address _to, uint256 _tokenId, bytes data) payable',
            a22cb465: 'function setApprovalForAll(address _operator, bool _approved)',
            '01ffc9a7': 'function supportsInterface(bytes4 interfaceID) view returns (bool)',
            '95d89b41': 'function symbol() view returns (string)',
            c87b56dd: 'function tokenURI(uint256 _tokenId) view returns (string)',
            '23b872dd': 'function transferFrom(address _from, address _to, uint256 _tokenId) payable'
        },
        events: {
            '8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925': 'event Approval(address indexed _owner, address indexed _approved, uint256 indexed _tokenId)',
            '17307eab39ab6107e8899845ad3d59bd9653f200f220920489ca2b5937696c31': 'event ApprovalForAll(address indexed _owner, address indexed _operator, bool _approved)',
            ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef: 'event Transfer(address indexed _from, address indexed _to, uint256 indexed _tokenId)'
        }
    }
};
