name: Test

on:
  # We want to trigger these jobs in every branch.
  push:
    # But do not trigger them when only `md` files were modified.
    paths-ignore:
      - '**.md'

# `FORCE_COLOR` is used by `chalk`, which is used internally by `mocha`.
# https://github.com/chalk/chalk#supportscolor
# https://github.com/orgs/community/discussions/26944#discussioncomment-3254075
env:
  FORCE_COLOR: 3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "NODE_VERSION=`node --version`" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn coverage
      - run: yarn bundle
      - name: Run Examples
        run: |
          node examples/Compound.mjs
          node examples/DAI.js
          node examples/UnicornToken.js
          node examples/USDC.js
